const output = document.getElementById("output");
const statusText = document.getElementById("status");

const generateBtn = document.getElementById("generateBtn");
const flashcardBtn = document.getElementById("flashcardBtn");
const pdfBtn = document.getElementById("pdfBtn");

const notesInput = document.getElementById("notesInput");
const questionType = document.getElementById("questionType");
const difficulty = document.getElementById("difficulty");
const questionCount = document.getElementById("questionCount");

function setStatus(text) {
  statusText.textContent = text;
}

function createQuestion(index, type, difficultyLevel) {
  return `
    <div class="question-card">
      <h3>Question ${index}</h3>
      <p><strong>Type:</strong> ${type}</p>
      <p><strong>Difficulty:</strong> ${difficultyLevel}</p>

      <ul>
        <li>A. Example Answer</li>
        <li>B. Example Answer</li>
        <li>C. Example Answer</li>
        <li>D. Example Answer</li>
      </ul>
    </div>
  `;
}

function createFlashcard(index) {
  return `
    <div class="flashcard">
      <h3>Flashcard ${index}</h3>
      <p><strong>Front:</strong> Example Concept</p>
      <p><strong>Back:</strong> Example Explanation generated by AI.</p>
    </div>
  `;
}

generateBtn.addEventListener("click", () => {

  output.innerHTML = "";

  const type = questionType.value;
  const diff = difficulty.value;
  const count = Number(questionCount.value);

  if (!notesInput.value.trim()) {
    alert("Please enter study notes first.");
    return;
  }

  setStatus("Generating Questions...");

  setTimeout(() => {

    for (let i = 1; i <= count; i++) {
      output.innerHTML += createQuestion(i, type, diff);
    }

    setStatus("Questions Generated");

  }, 1000);
});

flashcardBtn.addEventListener("click", () => {

  output.innerHTML = "";

  if (!notesInput.value.trim()) {
    alert("Please enter study notes first.");
    return;
  }

  setStatus("Generating Flashcards...");

  setTimeout(() => {

    for (let i = 1; i <= 10; i++) {
      output.innerHTML += createFlashcard(i);
    }

    setStatus("Flashcards Generated");

  }, 1000);
});

pdfBtn.addEventListener("click", () => {

  setStatus("Preparing PDF Export...");

  setTimeout(() => {
    alert("PDF Export system coming soon.");
    setStatus("Ready");
  }, 1000);
});
